### PR TITLE
Course Text Support

### PR DESCRIPTION
**Pull request by jrwagz**
This is in support of Issue #2

### CODE REVIEW

**Comment by jrwagz** [comment]
@kevinlsw what are your thoughts on these changes?  Anything else we should add/change before merging this in?

**Comment by kevinlsw** [comment]
Unfortunately we don't have much else to test against, so I think we are as good as we can be given what we have.

That option is disabled by default, so at least I don't think it will do any harm.  We can add in more modifications/fixes if we encounter files with different [COURSE TEXT] format in the future.

**Comment by jrwagz** [comment]
Will you review my documentation update for this feature?

Pull Request #6

**Comment by jrwagz** [comment]
:+1:

**Pull request merged**
